=== shlshl211/releasator/releasator-cli/src/changes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:chg="http://buildbox.sf.net/changes/2.0"
           targetNamespace="http://buildbox.sf.net/changes/2.0" elementFormDefault="qualified">
  <xs:element name="changes">
    <xs:annotation>
      <xs:documentation>developer's notes about work on a software</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="configuration" minOccurs="0">
          <xs:annotation>
            <xs:documentation>configuration properties providing high level of customization for release components, while still keeping track of these options</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="property" type="chg:ConfigurationProperty" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="known-issues" minOccurs="0">
          <xs:annotation>
            <xs:documentation>lists known issues of the project; in effect, can serve as a poor man's issue-tracking system</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" type="chg:Item" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:choice minOccurs="0">
          <xs:element name="unreleased">
            <xs:annotation>
              <xs:documentation>changes that were implemented and will appear in the next release. This part is intended
                for manual edits. Please do always add changes to the top.
              </xs:documentation>
            </xs:annotation>
            <xs:complexType>
              <xs:complexContent>
                <xs:extension base="chg:VersionNotes">
                  <!-- TODO: override cardinality of "item" element to allow 0-unbounded (descended cardinality is 1-unbounded)
                  <xs:choice>
                    <xs:element name="item" type="chg:Item" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:choice>
                  -->
                </xs:extension>
              </xs:complexContent>
            </xs:complexType>
          </xs:element>
          <xs:element name="localbuild" type="chg:BuiltVersionNotes">
            <xs:annotation>
              <xs:documentation>unreleased changes in distribution - created from "unreleased" by the build tool
              </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:choice>
        <xs:element name="release" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>describes released version. Usually created by a script from "unreleased" element during
              release
            </xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:complexContent>
              <xs:extension base="chg:BuiltVersionNotes">
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="IdentificationAttrs">
    <xs:attribute name="groupId" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="artifactId" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="version" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:attributeGroup name="BuildInfoAttrs">
    <xs:annotation>
      <xs:documentation>this information is typically filled automatically</xs:documentation>
    </xs:annotation>
    <xs:attribute name="timestamp" type="xs:dateTime" use="required">
      <xs:annotation>
        <xs:documentation>timestamp of the release</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="author" use="optional">
      <xs:annotation>
        <xs:documentation>free formated name of the person who initiated the release</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:complexType name="VcsInfo">
    <xs:annotation>
      <xs:documentation>information about storage in source code repository</xs:documentation>
    </xs:annotation>
    <xs:attribute name="id" use="required">
      <xs:annotation>
        <xs:documentation>identification of source code reposirory</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="location" use="required">
      <xs:annotation>
        <xs:documentation>path in the code repository at the time of development, starting with slash; for CVS, should be prefixed using
          cvs2svn-like convention ("/trunk/...", "/branches/BRANCHNAME/...")
        </xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="tag" use="required">
      <xs:annotation>
        <xs:documentation>path in the code repository at the time of release, starting with slash; for CVS, should be prefixed using
          cvs2svn-like convention ("/tags/TAGNAME/[path]")
        </xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="type" use="optional">
      <xs:annotation>
        <xs:documentation>type of version control, abbreviated; examples: "svn" (the implied default), "cvs", "git", "bzr", "hg", ...</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="revision" use="optional">
      <xs:annotation>
        <xs:documentation>the revision from which the release is initiated, i.e. before any commit to vcs</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="Item">
    <xs:annotation>
      <xs:documentation>individual change items</xs:documentation>
    </xs:annotation>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="action" use="optional">
          <xs:annotation>
            <xs:documentation>change type. If not specified, indicates either incompatible change or a change
              undetermined by migration heuristic
            </xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:NMTOKEN">
              <xs:enumeration value="add">
                <xs:annotation>
                  <xs:documentation>introduces a new feature in a way that does not hurt compatibility (note that
                    adding an interface method hurts!)
                  </xs:documentation>
                </xs:annotation>
              </xs:enumeration>
              <xs:enumeration value="fix">
                <xs:annotation>
                  <xs:documentation>describes a bugfix, which either does not impact compatibility or brings the
                    behavior closer to what was requested/expected.
                  </xs:documentation>
                </xs:annotation>
              </xs:enumeration>
              <xs:enumeration value="improve">
                <xs:annotation>
                  <xs:documentation>minor improvements and optimizations - something what keeps functionality
                    but gives it better quality
                  </xs:documentation>
                </xs:annotation>
              </xs:enumeration>
<!--
              <xs:enumeration value="refactor">
                <xs:annotation>
                  <xs:documentation>refactoring, renames and reorganization; often incompatible from one or more perspectives</xs:documentation>
                </xs:annotation>
              </xs:enumeration>
-->
              <xs:enumeration value="warning">
                <xs:annotation>
                  <xs:documentation>informs about something important - project abandoned, codebase moved,
                    identification changed etc.
                  </xs:documentation>
                </xs:annotation>
              </xs:enumeration>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="issue" use="optional">
          <xs:annotation>
            <xs:documentation>corresponding JIRA issue id if any</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="3"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="component" use="optional">
          <xs:annotation>
            <xs:documentation>name of the component or part relevant to this change</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="1"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="timestamp" use="optional" type="xs:dateTime">
          <xs:annotation>
            <xs:documentation>time of committing the change; should be entered by a tool, perhaps as part of a postcommit hook.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="reporter" use="optional">
          <xs:annotation>
            <xs:documentation>email of the person who found and reported the issue</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="3"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="resolver" use="optional">
          <xs:annotation>
            <xs:documentation>email of the person who is either assigned to resolve the issue (in issues), or who really did it (in version)</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="3"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="priority" use="optional">
          <xs:annotation>
            <xs:documentation>How fast should this be done. Having a todo with priority "blocker" should
              prevent the release tool from releasing production version.
              The processing details of other levels should yet be specified; they may end up as configurable.
            </xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="blocker"/>
              <xs:enumeration value="critical"/>
              <xs:enumeration value="major"/>
              <xs:enumeration value="minor"/>
              <xs:enumeration value="cosmetic"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="UpgradeProcedure">
    <xs:annotation>
      <xs:documentation>upgrade procedure for a specific (usually previous) version</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="from">
        <xs:complexType>
          <xs:attributeGroup ref="chg:IdentificationAttrs"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="step" minOccurs="1" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>steps that form a complete upgrade sequence</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="type" use="optional" type="xs:string">
                <xs:annotation>
                  <xs:documentation>step type; good values are for instance: sql-script, shell-script, program
                  </xs:documentation>
                </xs:annotation>
              </xs:attribute>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="VersionNotes" abstract="true">
    <xs:sequence>
      <xs:element name="item" type="chg:Item" maxOccurs="unbounded"/>
      <xs:element name="upgrade" type="chg:UpgradeProcedure" minOccurs="0" maxOccurs="unbounded"/>
      <xs:sequence>
        <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
      </xs:sequence>
    </xs:sequence>
    <xs:attribute name="codename" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attributeGroup ref="chg:IdentificationAttrs"/>
  </xs:complexType>
  <xs:complexType name="BuiltVersionNotes" abstract="true">
    <xs:complexContent>
      <xs:extension base="chg:VersionNotes">
        <xs:sequence>
          <xs:element name="buildtool" maxOccurs="unbounded">
            <xs:complexType>
              <xs:attribute name="role" type="xs:string"/>
              <xs:attributeGroup ref="chg:IdentificationAttrs"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="os" minOccurs="0">
            <xs:complexType>
              <xs:attribute name="arch" use="required"/>
              <xs:attribute name="name" use="required"/>
              <xs:attribute name="version" use="required"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="vcs" type="chg:VcsInfo"/>
          <xs:element name="module" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="artifact" minOccurs="1" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
                    </xs:sequence>
                    <xs:attribute name="classifier" use="optional"/>
                    <xs:attribute name="type" use="required"/>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
              <xs:attribute name="groupId" use="required"/>
              <xs:attribute name="artifactId" use="required"/>
              <xs:attribute name="version" use="required"/>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attributeGroup ref="chg:BuildInfoAttrs"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
      <xs:complexType name="ConfigurationProperty">
          <xs:annotation>
              <xs:documentation>currently supported properties are: cmdline.maven.arguments (goes to cmdline), maven.* (goes to release.properties)</xs:documentation>
          </xs:annotation>
          <xs:simpleContent>
              <xs:extension base="xs:string">
                  <xs:attribute name="name" use="required" type="xs:string"/>
              </xs:extension>
          </xs:simpleContent>
      </xs:complexType>
</xs:schema>

=== shlshl211/releasator/releasator-testdata/testsuites/sm-depplugin/expected/wc/tags/net.sf.buildbox.test-sm-depplugin-1.0.0-alpha-1/changes.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns="http://buildbox.sf.net/changes/2.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://buildbox.sf.net/changes/2.0 http://buildbox.sourceforge.net/releasator/changes.xsd">
    <configuration>
      <property name="maven-release-plugin.version">2.1</property>
    </configuration>
  <release groupId="net.sf.buildbox.test" artifactId="sm-depplugin" version="1.0.0-alpha-1" timestamp="2009-12-09T00:41:43.024Z" author="releasator@gmail.com">
    <item>test item desc</item>
    <buildtool role="release" groupId="org.apache.maven.plugins" artifactId="maven-release-plugin" version="2.1"/>
    <buildtool role="release" groupId="net.sf.buildbox" artifactId="releasator" version="1-SNAPSHOT-2009-12-09T00:39:38.057Z"/>
    <os arch="i386" name="Linux" version="2.6.31-16-generic"/>
    <vcs type="svn" id="local.svn" revision="14" location="/trunk/sm-depplugin" tag="/tags/net.sf.buildbox.test-sm-depplugin-1.0.0-alpha-1"/>
    <module groupId="net.sf.buildbox.test" artifactId="sm-depplugin" version="1.0.0-alpha-1">
      <artifact type="jar"/>
      <artifact type="pom"/>
    </module>
  </release>
</changes>

=== shlshl211/releasator/releasator-testdata/testsuites/mm-onechild/expected/wc/tags/net.sf.buildbox.test-mm-onechild-1.0.0-alpha-2/changes.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns="http://buildbox.sf.net/changes/2.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://buildbox.sf.net/changes/2.0 http://buildbox.sourceforge.net/releasator/changes.xsd">
  <release groupId="net.sf.buildbox.test" artifactId="mm-onechild" version="1.0.0-alpha-2" timestamp="2009-12-03T00:46:43.536Z" author="releasator@gmail.com" codename="container with one child">
    <item>test item description</item>
    <buildtool role="release" groupId="org.apache.maven.plugins" artifactId="maven-release-plugin" version="2.1"/>
    <buildtool role="release" groupId="net.sf.buildbox" artifactId="releasator" version="1-SNAPSHOT-2009-12-02T23:17:09.335Z"/>
    <os arch="i386" name="Linux" version="2.6.31-15-generic"/>
    <vcs type="svn" id="local.svn" revision="2" location="/trunk/mm-onechild" tag="net.sf.buildbox.test-mm-onechild-1.0.0-alpha-2"/>
    <module groupId="net.sf.buildbox.test" artifactId="mm-onechild" version="1.0.0-alpha-2">
      <artifact type="pom"/>
    </module>
    <module groupId="net.sf.buildbox.test" artifactId="mm-onechild-solo" version="1.0.0-alpha-2">
      <artifact type="jar"/>
      <artifact type="pom"/>
    </module>
  </release>
</changes>

=== shlshl211/releasator/releasator-testdata/testsuites/mm-twins/expected/wc/tags/net.sf.buildbox.test-mm-twins-1.0.0-alpha-3/changes.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns="http://buildbox.sf.net/changes/2.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://buildbox.sf.net/changes/2.0 http://buildbox.sourceforge.net/releasator/changes.xsd">
    <configuration>
      <property name="maven-release-plugin.version">2.1</property>
    </configuration>
  <release groupId="net.sf.buildbox.test" artifactId="mm-twins" version="1.0.0-alpha-3" timestamp="2009-12-03T17:04:19.041Z" author="releasator@gmail.com" codename="container with two children">
    <item>test item description</item>
    <buildtool role="release" groupId="org.apache.maven.plugins" artifactId="maven-release-plugin" version="2.1"/>
    <buildtool role="release" groupId="net.sf.buildbox" artifactId="releasator" version="1-SNAPSHOT-2009-12-03T17:00:18.668Z"/>
    <os arch="i386" name="Linux" version="2.6.31-15-generic"/>
    <vcs type="svn" id="local.svn" revision="8" location="/trunk/mm-twins" tag="/tags/net.sf.buildbox.test-mm-twins-1.0.0-alpha-3"/>
    <module groupId="net.sf.buildbox.test" artifactId="mm-twins" version="1.0.0-alpha-3">
      <artifact type="pom"/>
    </module>
    <module groupId="net.sf.buildbox.test" artifactId="twins-prima" version="1.0.0-alpha-3">
      <artifact type="jar"/>
      <artifact type="pom"/>
    </module>
    <module groupId="net.sf.buildbox.test" artifactId="twins-seconda" version="1.0.0-alpha-3">
      <artifact type="jar"/>
      <artifact type="pom"/>
    </module>
  </release>
</changes>

=== shlshl211/releasator/releasator-testdata/testsuites/underworld-simple/expected/wc/underworld/tags/net.sf.buildbox.test-test-simple-1.0.0-alpha-1/changes.xml
<?xml version="1.0" encoding="UTF-8"?>
<changes xmlns="http://buildbox.sf.net/changes/2.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://buildbox.sf.net/changes/2.0 http://buildbox.sourceforge.net/releasator/changes.xsd">
  <configuration>
    <property name="maven-release-plugin.version">2.0-beta-9</property>
  </configuration>
  <release groupId="net.sf.buildbox.test" artifactId="test-simple" version="1.0.0-alpha-1" timestamp="2009-12-09T00:41:43.024Z" author="releasator@gmail.com" codename="simple jar module">
    <item>test item desc</item>
    <buildtool role="release" groupId="org.apache.maven.plugins" artifactId="maven-release-plugin" version="2.0-beta-9"/>
    <buildtool role="release" groupId="net.sf.buildbox" artifactId="releasator" version="1-SNAPSHOT-2009-12-09T00:39:38.057Z"/>
    <os arch="i386" name="Linux" version="2.6.31-16-generic"/>
    <vcs type="svn" id="local.svn" revision="20" location="/underworld/trunk/single" tag="/underworld/tags/net.sf.buildbox.test-test-simple-1.0.0-alpha-1"/>
    <module groupId="net.sf.buildbox.test" artifactId="test-simple" version="1.0.0-alpha-1">
      <artifact type="jar"/>
      <artifact type="pom"/>
    </module>
  </release>
</changes>
